# Generated by Django 3.0.4 on 2020-08-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_title', models.CharField(max_length=100)),
                ('thread_text', models.CharField(max_length=5000)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Date published')),
                ('category', models.CharField(choices=[('Random', 'Random'), ('Broadcast', 'Broadcast'), ('Animation', 'Animation'), ('Artwork', 'Artwork'), ('Cinematics', 'Cinematics'), ('Videogames', 'Videogames')], max_length=100)),
                ('thread_author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=2500)),
                ('comment_author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date published')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_id', to='board.Thread')),
            ],
        ),
    ]
