TITLE_BOARD = ['Board', 'Доска']
POSTED = ['Posted @', 'Пост от']
REPLIED = ['Replied @', 'Ответ от']
AUTHOR = ['thread author', 'автор треда']
REPLY_TO_THREAD = ['Reply to thread', 'Ответить']
REMOVE = ['Remove', 'Удалить']
