# Generated by Django 2.2.5 on 2019-10-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikkaHq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date_c',
            field=models.DateTimeField(default='null', verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
    ]
