# Generated by Django 2.2.5 on 2019-10-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikkaHq', '0002_auto_20191015_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date_c',
            field=models.DateTimeField(default='0000-00-00 00:00', verbose_name='Date published'),
        ),
    ]
