# Generated by Django 2.2.5 on 2019-10-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikkaHq', '0003_auto_20191015_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date_c',
            field=models.DateTimeField(default='none', verbose_name='Date published'),
        ),
    ]
