# Generated by Django 2.2.5 on 2019-10-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikkaHq', '0006_auto_20191015_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date_c',
            field=models.DateTimeField(default='000-00-00 00:00[:00[.000000]][GB]', verbose_name='Date published'),
        ),
    ]
