# Generated by Django 2.2.5 on 2019-10-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikkaHq', '0008_auto_20191015_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date_c',
            field=models.DateTimeField(null=True, verbose_name='Date published'),
        ),
    ]
