# Generated by Django 2.2.5 on 2019-10-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikkaHq', '0009_auto_20191015_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date_c',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
    ]
