# Generated by Django 2.2.5 on 2019-10-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikkaHq', '0011_remove_comment_pub_date_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date_c',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date published'),
        ),
    ]
