# Generated by Django 2.2.5 on 2019-10-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikkaHq', '0014_auto_20191015_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date published'),
        ),
    ]
