CREATE = ['Create a thread', 'Создать тред']
BROADCAST = ['Broadcast', 'Вещание']
ANIMATION = ['Animation', 'Анимация']
ARTWORK = ['Artwork', 'Искусство']
CINEMATICS = ['Cinematics', 'Кинематограф']
VIDEOGAMES = ['Videogames', 'Игры']
RANDOM = ['Random', 'Бред']
